solver_choice = 'network-simplex'
started_nodes = []
ID = []
earliness = []
tardiness = []
filepath = ""
H = 0
d = 0
num_max_agvs = 0
numOfAGVs = 0
count = 0
reachingTargetAGVs = 0
haltingAGVs = 0
totalCost = 0
#sfm = False
functions_file = "functions.txt"
totalSolving = 0
timeSolving = 0
level_of_simulation = 0 #0 - "Fully Random", 1 - "Random in the list", 2 - "SFM"
test_automation = 0
draw = 0
M = 0
restrictions_data_cache = [[[[4, 1], [1, 2]], [2, 5], 1, 1.0, None, 2.0]]
restrictions_are_set_in_cache = False